"""Write STATUS.md from sync/manifest.json.

    python tools/status.py

One table per kind, one row per item: its status, the upstream files it ports and the note. The
Not ported section is kept from the existing file, under its heading, so a reason survives a
regeneration.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent
MANIFEST = HERE / "sync" / "manifest.json"
STATUS = HERE / "STATUS.md"

KINDS = [
    ("core", "Core"),
    ("primitives", "Theme, workers, icons and primitives"),
    ("widgets", "Widgets"),
    ("demos", "Demos and the showcase"),
    ("docs", "Docs pages"),
]

HEAD = """# Status

What is ported from `~/dev/sg-widgets`, what is partial, what is left. Generated by
`python tools/status.py` from `sync/manifest.json`; `python tools/sync_status.py` says what drifted
upstream since. Only the Not ported section is written by hand.
"""


def kept_not_ported(text: str) -> str:
    m = re.search(r"^## Not ported\n.*", text, re.S | re.M)
    return m.group(0).rstrip() + "\n" if m else "## Not ported\n\n| upstream | reason |\n|---|---|\n"


def main() -> int:
    data = json.loads(MANIFEST.read_text())
    items = data["items"]
    out = [HEAD]
    commit = data.get("upstream", {}).get("commit", "")
    if commit:
        out.append(f"\nLast synced upstream commit: `{commit[:12]}`.\n")
    counts = {}
    for name, item in items.items():
        kind = name.split("/")[0]
        counts.setdefault(kind, {"complete": 0, "partial": 0, "skipped": 0})
        counts[kind][item["status"]] = counts[kind].get(item["status"], 0) + 1
    out.append("\n| kind | complete | partial | skipped |\n|---|---|---|---|\n")
    for kind, title in KINDS:
        c = counts.get(kind, {})
        out.append(f"| {title} | {c.get('complete', 0)} | {c.get('partial', 0)} | {c.get('skipped', 0)} |\n")
    for kind, title in KINDS:
        rows = [(n, i) for n, i in items.items() if n.split("/")[0] == kind]
        if not rows:
            continue
        out.append(f"\n## {title}\n\n| item | status | ports | note |\n|---|---|---|---|\n")
        for name, item in sorted(rows):
            ports = ", ".join(f"`{Path(p).name}`" for p in item["upstream"])
            note = item.get("note", "").replace("|", "\\|")
            out.append(f"| {name.split('/', 1)[1]} | {item['status']} | {ports} | {note} |\n")
    existing = STATUS.read_text() if STATUS.exists() else ""
    out.append("\n" + kept_not_ported(existing))
    STATUS.write_text("".join(out))
    print(f"STATUS.md: {len(items)} items")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
